name: Deploy Expo Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Build web version
        run: npx expo export:web

      - name: Configure for GitHub Pages
        run: |
          cd web-build
          cp index.html 404.html
          echo "// Fix para rutas en GitHub Pages" > gh-pages-fix.js
          echo "if (window.location.pathname.startsWith('/Julis-Cakes') && window.location.pathname !== '/Julis-Cakes/') {" >> gh-pages-fix.js
          echo "  const withoutPrefix = window.location.pathname.replace(/^\\/Julis-Cakes/, '');" >> gh-pages-fix.js
          echo "  window.history.replaceState(null, null, withoutPrefix || '/');" >> gh-pages-fix.js
          echo "}" >> gh-pages-fix.js
          sed -i '/<head>/a <script src="gh-pages-fix.js"></script>' index.html
          sed -i '/<head>/a <script src="gh-pages-fix.js"></script>' 404.html
          # Asegurar que las rutas son relativas en lugar de absolutas
          sed -i 's|href="/|href="./|g' index.html
          sed -i 's|href="/|href="./|g' 404.html
          sed -i 's|src="/|src="./|g' index.html
          sed -i 's|src="/|src="./|g' 404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web-build