name: Convert Markdown to HTML and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # 3. Instalar `marked`
    - name: Install Marked (Markdown to HTML converter)
      run: npm install -g marked

    # 4. Convertir todos los archivos Markdown a HTML
    - name: Convert Markdown files to HTML
      run: |
        mkdir -p docs
        for file in *.md; do
          [ -f "$file" ] || break
          marked -o "docs/${file%.md}.html" "$file"
        done

    # 5. Commit y push de los archivos generados
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add docs/
        git commit -m "Deploy Markdown to HTML via GitHub Actions"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
