name: Convert Markdown to HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Descargar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # 3. Instalar dependencias (marked)
    - name: Install dependencies
      run: npm install marked@latest

    # 4. Ejecutar el script para generar HTML
    - name: Generate HTML files
      run: node generate-html.js

    # 5. Actualizar el archivo index.html con las recetas
    - name: Update index.html
      run: |
        echo "<!DOCTYPE html>" > index.html
        echo "<html lang='es'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'><title>Julis Cakes</title><link rel='stylesheet' href='styles.css'></head><body><header><h1>🎂 Julis Cakes</h1></header><main><h2>Recetas Disponibles</h2><ul>" >> index.html
        for file in rendered/*.html; do
          [ "$file" != "rendered/template.html" ] || continue
          filename=$(basename "$file")
          title=$(basename "$file" .html | sed 's/_/ /g; s/\b\(.\)/\u\1/g') # Convertir a título amigable
          echo "<li><a href='rendered/$filename'>$title</a></li>" >> index.html
        done
        echo "</ul></main><footer><p>© 2025 Julis Cakes</p></footer></body></html>" >> index.html

    # 6. Subir los cambios al repositorio
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add rendered/*.html index.html
        git commit -m "Convert Markdown to HTML and update index"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
